# Generated by Django 5.0.2 on 2024-02-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legaldb',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='legaldb',
            old_name='legal_types',
            new_name='LegalTypes',
        ),
        migrations.RenameField(
            model_name='legaldb',
            old_name='price',
            new_name='Price',
        ),
    ]
