# Generated by Django 5.0.2 on 2024-02-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_description_legaldb_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc_cmpny', models.TextField(blank=True, max_length=50, null=True)),
                ('Comp_Image', models.ImageField(blank=True, null=True, upload_to='Company media')),
                ('ContactNo', models.IntegerField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='legaldb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
