# Generated by Django 5.0.2 on 2024-02-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_companydb_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='legalimages'),
        ),
    ]
