# Generated by Django 5.0.2 on 2024-03-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_userdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerdb',
            name='Mob_No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
