# Generated by Django 5.0.2 on 2024-03-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_rename_password_userdb_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerdb',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
