# Generated by Django 5.0.2 on 2024-03-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_lawyerdb_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerdb',
            name='payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
