# Generated by Django 5.0.2 on 2024-03-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_alter_lawyerdb_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerdb',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
