# Generated by Django 5.0.2 on 2024-03-14 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_alter_lawyerdb_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.lawyerdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.userdb')),
            ],
        ),
    ]
