# Generated by Django 5.0.2 on 2024-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_requestdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdb',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='requestdb',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
