# Generated by Django 5.0.3 on 2025-03-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_customerrequest_delete_requestdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('Lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.lawyerdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.userdb')),
            ],
        ),
    ]
