# Generated by Django 5.0.3 on 2025-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_booking_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
