# Generated by Django 5.0.3 on 2025-03-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_booking_model_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
