# Generated by Django 5.0.3 on 2025-04-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_alter_userdb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
